### ISSUE TITLE
14PM iOS17.0 巨魔安装测试成功，版本17_101

### ISSUE THREAD

**Issue by liceven** [xybp888/TrollStoreApp#1]
17.0 巨魔安装测试成功，版本17_101

**Comment by liceven** [comment]
反馈个问题，14PM iOS17.0 安装后 点通讯录-我的名片  会闪退

**Comment by wotaifu-tairuibao** [comment]
你好，反馈一个问题，ios17中设置过海报的联系人点击闪退

**Comment by xybp888** [comment]
> 你好，反馈一个问题，ios17中设置过海报的联系人点击闪退



> 反馈个问题，14PM iOS17.0 安装后 点通讯录-我的名片 会闪退

可能是系统问题
